### ISSUE TITLE
Is this actively being worked on or has it died?

### ISSUE THREAD

**Issue by MagnAxiom** [westdavidr/youngliving-node#2]
Is this actively being worked on or has it died?

**Comment by wcalebgray** [comment]
+1 I'd be willing to help out to add more functionality

**Comment by westdavidr** [comment]
@MagnAxiom It kinda died out. I haven't had a use for it in a while. 

@wcalebgray Feel free to contribute!

**Comment by wcalebgray** [comment]
@westdavidr are you getting documentation from YL somewhere? How were you able to start on this? I have experience in wrapping an already existing API (e.g. from Young Living) but not in constructing one blindly.

**Comment by westdavidr** [comment]
@wcalebgray I was able to find what I needed by using Chrome Dev Tools on the YL website.

**Comment by westdavidr** [comment]
@wcalebgray I wrote up some documentation a while back - not sure how much of it is still valid.

https://gist.github.com/westdavidr/c8890e46a8f06b92df85

**Comment by seanriceaz** [comment]
I've got a project I'm working on that needs this. I've committed a bugfix. It would be great to get access to publish releases on this repo though so I can try to get it listed in NPM (if we still care to do that).
